### PR TITLE
feat/selenium

### PR DESCRIPTION
**Pull request by disturbing**
This change is [Reviewable](https://reviewable.io/reviews/kintohub/charts/6)

### CODE REVIEW

**Comment by disturbing** [comment]
hub.image=selenium/hub
hub.tag=3.141.59
chrome.enabled=false
chrome.replicas=1
chromeDebug.enabled=false
chromeDebug.replicas=1
firefox.enabled=false
firefox.replicas=1
firefoxDebug.enabled=false
firefoxDebug.replicas=1

**Comment by bakayolo** [comment]
Same

```
hub.image=selenium/hub
hub.tag=3.141.59
chrome.enabled=false
chrome.replicas=1
chromeDebug.enabled=false
chromeDebug.replicas=1
firefox.enabled=false
firefox.replicas=1
firefoxDebug.enabled=false
firefoxDebug.replicas=1
```

Suggest to put these values in `values.kinto` for reference

**Review by bakayolo — CHANGES_REQUESTED** [review]
In NOTES.txt

Remove `.{{ .Release.Namespace }}:{{ .Values.hub.port }}`

and

```
You can easily connect to the remote instance from your browser. Forward the
webserver port to localhost:4444	webserver port to localhost:4444
- kubectl port-forward --namespace {{ .Release.Namespace }} \	- kubectl port-forward --namespace {{ .Release.Namespace }} \
  $(kubectl get pods --namespace {{ .Release.Namespace }} \	  $(kubectl get pods --namespace {{ .Release.Namespace }} \
    -l app={{ template "selenium.hub.fullname" . }} \	    -l app={{ template "selenium.hub.fullname" . }} \
    -o jsonpath='{ .items[0].metadata.name }') 4444	    -o jsonpath='{ .items[0].metadata.name }') 4444
```

**Comment by bakayolo** [comment]
You are missing the resources limit.

**Pull request merged**
